### ISSUE TITLE
unable to import

### ISSUE THREAD

**Issue by MIQted** [khoadng/Boorusama#438]
![IMG_20240715_145707_988](https://github.com/user-attachments/assets/d14ec319-144c-4723-a10c-d38bf2a55407)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by khoadng** [comment]
Please fill out the necessary information.

**Comment by Tryoskasen** [comment]
this issue same to me.

**detail information**

**Bug**

cannot import boorus profile, bookmarks, and setting

**To reproduce**

1. open setting
2. select backup and restore
3. select bookmarks to import
5. error encounter as first comment
6. tried boorus profile and bookmarks. the result same
7. reinstall the app
8. error still encounter

**Expected behavior**
opening default file manager android

**Screenshot**
![1](https://github.com/user-attachments/assets/458d0e6e-d9c3-467b-9eda-dc8fb2618dd4)

**Smartphones**

- Device : Redmi 6A
- OS : Android 9

**Additional Context**
when I select export, there is no problem. I assume from the error is file type extension are not written correctly when importing. However, when I'm using Redmi Note 9 Android 12 there are no problem

**Comment by khoadng** [comment]
@Tryoskasen 
Thanks for the information!
I think there is an issue with file picker on older Android version. I will take a look this weekend.
